# Settings keys
REDDIT_USERNAME = "REDDIT_USERNAME"
REDDIT_EMAIL = "REDDIT_EMAIL"
REDDIT_PASSWORD = "REDDIT_PASSWORD"
REDDIT_CLIENT_ID = "REDDIT_CLIENT_ID"
REDDIT_CLIENT_SECRET = "REDDIT_CLIENT_SECRET"
REDDIT_USER_AGENT = "REDDIT_USER_AGENT"

SUBREDDIT_TYPE = ["user", "public", "restricted"]
