from decouple import config

REDDIT_USERNAME = config("REDDIT_USERNAME")
REDDIT_EMAIL = config("REDDIT_EMAIL")
REDDIT_PASSWORD = config("REDDIT_PASSWORD")
REDDIT_CLIENT_ID = config("REDDIT_CLIENT_ID")
REDDIT_CLIENT_SECRET = config("REDDIT_CLIENT_SECRET")
REDDIT_USER_AGENT = config("REDDIT_USER_AGENT")
